### ISSUE TITLE
fine-tune policy

### ISSUE THREAD

**Issue by developer0hye** [facebookresearch/semi-supervised-ImageNet1K-models#4]
Thank you for sharing the great research.

I want to apply your training method to my project.

When we fine-tune the model with the labeled dataset, do we fine-tune the last layer of the network or train the all layers of the network?

**Comment by fbzekiyalniz** [comment]
Thank you for the feedback Yonghye!

Regarding your question, it is up to your ultimate goal. If you want to evaluate the representation power of your trunk model, you would fine-tune only the last fully connected layer. If you would like to get the best results for the task task, you can finetune the entire network, which is more effective than fine-tuning the last layer.  Does this answer your question?

**Comment by developer0hye** [comment]
@fbzekiyalniz 
Thanks! It works really well.
