### ISSUE TITLE
Share models before fine-tuning

### ISSUE THREAD

**Issue by saareliad** [facebookresearch/semi-supervised-ImageNet1K-models#5]
For studying/replicating the fine-tuning on imagenet, we are looking for the pre-trained models before fine-tuning,
is it possible to share them as well?

See also https://github.com/facebookresearch/WSL-Images/issues/8

**Comment by fbzekiyalniz** [comment]
Unfortunately, the pretrained models are not going to be released. Thanks for the inquiry.
